daemon off;

events {}

http {
    include mime.types;

    server {
        listen 5173;
        server_name localhost;

        root ./dist;
        index index.html;

        location / {
            try_files $uri $uri/ /index.html;

        }

        access_log ./access_log;
        error_log ./error_log;
    }
}
